# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Deno

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@c7d7968ad4a59c159a777f79adddad6872ee8d96
        with:
          deno-version: "v1.x"
    
      - name: Make README
        run: deno run -A scripts/makeReadme.ts
        
      - name: Push to GitHub
        run: git add README.md && git commit -m "Update README" && git push
